### ISSUE TITLE
Pre-commit hook for automatic formatting and linting

### ISSUE THREAD

**Issue by vprusso** [vprusso/toqito#912]
We should add a pre-commit hook to catch any linting or formatting issues. Adding a `pre-commit-config.yaml` in the root directory of the project that looks like:

```yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version (keep in sync with the version in pyproject.toml)
  rev: v0.7.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
```

Additionally, add the following under the contribution instructions: 

```
To guarantee that both linter and formatter run before each commit, 
please install the pre-commit hook with
```sh
poetry run pre-commit install
```
